applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/andreyzp87/goit-devops-tasks.git
      path: docker-django/django
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app-repo
    url: https://github.com/andreyzp87/goit-devops-tasks.git
    username: andreyzp87
    password: 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

repoConfig:
  insecure: "true"
  enableLfs: "true"
