version: '3.8'

services:
  db:
    image: postgres:15
    container_name: goit_django_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "59432:5432"

  web:
    build:
      context: ./django
    container_name: goit_django_app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./django/testproject:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: goit_django_nginx
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
