replicaCount: 1

image:
  repository: 704428060658.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-django-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

django:
  config:
    POSTGRES_HOST: db
    POSTGRES_POR: 5432
    POSTGRES_DB: django
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
